server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/registration
    username:
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
